server:
  tomcat:
    uri-encoding: UTF-8
    remote-ip-header: x-forwarded-for
  use-forward-headers: true

management:
  security:
    enabled: false

spring:
  aop:
    proxy-target-class: true
    auto: true
  rabbitmq:
    host: paascloud-mq-rabbit
    port: 5672
    username: guest
    password: guest
  redis:
    host: paascloud-db-redis
    password: root
    port: 6379
    timeout: 0
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat,wall
    druid:
      initial-size: 50
      min-idle: 50
      max-active: 100
      test-on-borrow: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      web-stat-filter:
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      stat-view-servlet:
        allow:
        login-username: admin
        login-password: admin
  mail:
    host: smtp.126.com
    username: miniservertest@126.com
    password: 1q2w3e4r5t
    port: 465
    protocol: smtp
    test-connection: false
    default-encoding: UTF-8
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
          starttls:
            enable: true
            required: true
  boot:
    admin:
      username: admin
      password: admin
  zipkin:
    rabbitmq:
      queue: zipkin
  sleuth:
    sampler:
      percentage: 0.2

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

ribbon:
  eager-load:
    enabled: true
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  OkToRetryOnAllOperations: false
  ConnectTimeout: 60000
  ReadTimeout: 20000

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 20000

info:
  软件著作权: paascloud快速搭建企业级分布式微服务平台
  著作登记号: 2018SR320076
  关于我们: http://paascloud.net

paascloud:
  auth:
    jwt:
      expiredRemainMinutes: 20
      expiredMinutes: 120
  aliyun:
    key:
      accessKeyId: 'your aliyun accessKeyId'
      accessKeySecret: 'your aliyun accessKeySecret'
    rocketMq:
      namesrvAddr: paascloud-mq-rocket:9876
    sms:
      signName: 快乐学习网
      regionId: cn-beijing
      endpoint:
      endpointName: cn-beijing
      product: 'your sms product'
      domain: dysmsapi.aliyuncs.com
  qiniu:
    key:
      accessKey: 'YxW2_V1FQj2yOYNlHlzhHiAHI4cwWkPWNIxiT_ae'
      secretKey: '1d1Uo7S3x7qJXSL8ljbW46b2dKgWL0fPjHxG4PdI'
    oss:
      privateHost: 'your qiniu oss private host'
      publicHost: 'psb7edjec.bkt.clouddn.com'
  alipay:
    callback:
      url: http://dev-api.paascloud.net/omc/pay/alipayCallback
    qrCode:
      pcPath: /data/file/qrCode/alipay
      qiniuPath: alipay/QRCode/
  zk:
    zkAddressList: paascloud-provider-zk:2181
  database:
    driverClassName: com.mysql.jdbc.Driver
    initialSize: 50
    minIdle: 50
    maxActive: 100
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    druid[0]:
      appId: paascloud_uac
      name: paascloud_uac
      host: paascloud-db-mysql
      port: 3306
      username: root
      password: 123456
      initstance: uac,omc
    druid[1]:
      appId: paascloud_mdc
      name: paascloud_mdc
      host: paascloud-db-mysql
      port: 3306
      username: root
      password: 123456
      initstance: uac,omc
    druid[2]:
      appId: paascloud_omc
      name: paascloud_omc
      host: paascloud-db-mysql
      port: 3306
      username: root
      password: 123456
      initstance: uac,omc
    druid[3]:
      appId: paascloud_opc
      name: paascloud_opc
      host: paascloud-db-mysql
      port: 3306
      username: root
      password: 123456
      initstance: uac,omc
    druid[4]:
      appId: paascloud_tpc
      name: paascloud_tpc
      host: paascloud-db-mysql
      port: 3306
      username: root
      password: 123456
      initstance: uac,omc
    druid[5]:
      appId: exampleId1234
      name: exampleId1234
      host: paascloud-db-mysql
      port: 3306
      username: root
      password: 123456
      initstance: uac,omc
    druid[6]:
      appId: wx7b7aabca0fc1737d
      name: wx7b7aabca0fc1737d
      host: paascloud-db-mysql
      port: 3306
      username: root
      password: 123456
      initstance: uac,omc
